### 設定の流れ ###
# 1.権限の設定
# 2.Dockerを使う
# 3.コンテナを起動
# 4.DB準備
# 5.テスト実行

sudo: required # 1

services: docker # 2

before_install: # 4
  - cd product-register/
  - docker-compose up --build -d

script: # 4,5
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test